sonar.projectKey=AGV48_Encuentros-Back
sonar.organization=agv48
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Excluir módulos que no son de tu responsabilidad
sonar.exclusions=**/*.module.ts,**/main.ts,src/chat/**,src/encuentro/**,src/auth/**

# Incluir solo tu módulo de amistades (users)
sonar.inclusions=src/users/**