sonar.projectKey=agv48_encuentros-back
sonar.organization=agv48
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.module.ts,**/main.ts